.TH "CHECKMAILS" "1" "April 2017" "checkmails 1.2.3" ""
.SH NAME
CheckMails \- System tray unread mail checker
.SH SYNOPSIS
.B checkmails
.SH DESCRIPTION
CheckMails periodically looks for unread mails and displays the total number
of unread mails in the system tray icon. Several mailboxes can be configured.
The number of unread mails for each mailbox is detailed in a notification
that appears when clicking on the icon and after a check. This application
supports only IMAP protocol with SSL encryption. The connection information
for each mailbox is stored in an encrypted file using a master password.
.SH AUTHOR
CheckMails is developped by Juliette Monsel <j_4321@protonmail.com>
.SH BUGS
Please submit bugs on the Github page of the project
\fBhttps://github.com/j4321/CheckMails/issues\fR.
